### ISSUE TITLE
The conversationSignature is not set and is required to ensure that you have permission to use our APIs. IsAuthenticated=False. App ID=

### ISSUE THREAD

**Issue by Kimi0n** [transitive-bullshit/bing-chat#27]
The previous issue was closed without a solution. 
I get this message, no matter how recent my _u cookie is even though i have access to the new bing. Any solutions?

**Comment by IceCream0910** [comment]
I published an earlier issue, and in my case, there was a typo in the cookie value. Try copying and modifying the `_U` value again.

**Comment by Kimi0n** [comment]
Modifying the _U value? I just copy pasted it and it didn't work

**Comment by alectrocute** [comment]
Same issue here. Maybe Bing finally locked things down on their end.

```
wss://sydney.bing.com/sydney/ChatHub {
  "arguments": [
    {
      "source": "cib",
      "optionsSets": [
        "nlu_direct_response_filter",
        "deepleo",
        "enable_debug_commands",
        "disable_emoji_spoken_text",
        "responsible_ai_policy_235",
        "enablemm",
        "galileo"
      ],
      "allowedMessageTypes": [
        "Chat",
        "InternalSearchQuery",
        "InternalSearchResult",
        "InternalLoaderMessage",
        "RenderCardRequest",
        "AdsQuery",
        "SemanticSerp"
      ],
      "sliceIds": [],
      "traceId": "6385162610d4b7b6ec204b010251f2d2",
      "isStartOfSession": true,
      "message": {
        "locale": "en-US",
        "market": "en-US",
        "region": "US",
        "author": "user",
        "inputMethod": "Keyboard",
        "messageType": "Chat",
        "text": "How does Reddit work?"
      },
      "participant": {}
    }
  ],
  "invocationId": "1",
  "target": "chat",
  "type": 4
}
RESPONSE {
  "type": 2,
  "invocationId": "1",
  "item": {
    "firstNewMessageIndex": null,
    "conversationId": "04389fe6-50e2-4616-8bc2-d79bf7c42c7e",
    "requestId": "f53da9ff-a189-4ade-843c-8cb8ddad0661",
    "telemetry": {
      "metrics": null,
      "startTime": "2023-03-27T16:31:19.2120335Z"
    },
    "result": {
      "value": "UnauthorizedRequest",
      "message": "The conversationSignature is not set and is required to ensure that you have permission to use our APIs. IsAuthenticated=False. App ID=",
      "error": "UnauthorizedRequest",
      "renewCert": true,
      "serviceVersion": "20230326.3"
    }
  }
}
```

**Comment by PeterNjeim** [comment]
you need `KievRPSSecAuth` in addition to `_U`, separate the two key-value pairs with a semicolon, like: `KievRPSSecAuth=stuff;_U=stuff`

**Comment by lunaratom** [comment]
> you need `KievRPSSecAuth` in addition to `_U`, separate the two key-value pairs with a semicolon, like: `KievRPSSecAuth=stuff;_U=stuff`

I have all the required cookies in my .json but I still get the `conversationSignature` error. Can you please help me out?
